defmodule WebAnalytics.Geo.Countries do
  @moduledoc """
  ISO 3166-1 country names and an IANA time-zone to country map.

  Both tables are generated from the system tz database (`iso3166.tab` and
  `zone.tab`), which is the same source browsers and operating systems agree on.
  They are compiled in as literal maps so lookups are constant-time and need no
  process, file or dependency.

  A handful of country names are overridden where the tz database's spelling
  reads oddly on a chart — "Britain (UK)" becomes "United Kingdom", "Korea
  (South)" becomes "South Korea", and so on. Everything else is used verbatim.

  The time-zone table exists only as a last-resort fallback: a browser always
  reports its zone, so a country can be guessed even with no GeoIP database and
  no CDN headers. It is a guess about *country* and nothing finer — a zone name
  like `America/Los_Angeles` names the zone's reference city, not the visitor's,
  so it is never used to infer a city.
  """

  @countries %{
    "AD" => "Andorra",
    "AE" => "United Arab Emirates",
    "AF" => "Afghanistan",
    "AG" => "Antigua & Barbuda",
    "AI" => "Anguilla",
    "AL" => "Albania",
    "AM" => "Armenia",
    "AO" => "Angola",
    "AQ" => "Antarctica",
    "AR" => "Argentina",
    "AS" => "Samoa (American)",
    "AT" => "Austria",
    "AU" => "Australia",
    "AW" => "Aruba",
    "AX" => "Åland Islands",
    "AZ" => "Azerbaijan",
    "BA" => "Bosnia & Herzegovina",
    "BB" => "Barbados",
    "BD" => "Bangladesh",
    "BE" => "Belgium",
    "BF" => "Burkina Faso",
    "BG" => "Bulgaria",
    "BH" => "Bahrain",
    "BI" => "Burundi",
    "BJ" => "Benin",
    "BL" => "St Barthelemy",
    "BM" => "Bermuda",
    "BN" => "Brunei",
    "BO" => "Bolivia",
    "BQ" => "Caribbean NL",
    "BR" => "Brazil",
    "BS" => "Bahamas",
    "BT" => "Bhutan",
    "BV" => "Bouvet Island",
    "BW" => "Botswana",
    "BY" => "Belarus",
    "BZ" => "Belize",
    "CA" => "Canada",
    "CC" => "Cocos (Keeling) Islands",
    "CD" => "DR Congo",
    "CF" => "Central African Rep.",
    "CG" => "Republic of the Congo",
    "CH" => "Switzerland",
    "CI" => "Côte d’Ivoire",
    "CK" => "Cook Islands",
    "CL" => "Chile",
    "CM" => "Cameroon",
    "CN" => "China",
    "CO" => "Colombia",
    "CR" => "Costa Rica",
    "CU" => "Cuba",
    "CV" => "Cape Verde",
    "CW" => "Curaçao",
    "CX" => "Christmas Island",
    "CY" => "Cyprus",
    "CZ" => "Czechia",
    "DE" => "Germany",
    "DJ" => "Djibouti",
    "DK" => "Denmark",
    "DM" => "Dominica",
    "DO" => "Dominican Republic",
    "DZ" => "Algeria",
    "EC" => "Ecuador",
    "EE" => "Estonia",
    "EG" => "Egypt",
    "EH" => "Western Sahara",
    "ER" => "Eritrea",
    "ES" => "Spain",
    "ET" => "Ethiopia",
    "FI" => "Finland",
    "FJ" => "Fiji",
    "FK" => "Falkland Islands",
    "FM" => "Micronesia",
    "FO" => "Faroe Islands",
    "FR" => "France",
    "GA" => "Gabon",
    "GB" => "United Kingdom",
    "GD" => "Grenada",
    "GE" => "Georgia",
    "GF" => "French Guiana",
    "GG" => "Guernsey",
    "GH" => "Ghana",
    "GI" => "Gibraltar",
    "GL" => "Greenland",
    "GM" => "Gambia",
    "GN" => "Guinea",
    "GP" => "Guadeloupe",
    "GQ" => "Equatorial Guinea",
    "GR" => "Greece",
    "GS" => "South Georgia & the South Sandwich Islands",
    "GT" => "Guatemala",
    "GU" => "Guam",
    "GW" => "Guinea-Bissau",
    "GY" => "Guyana",
    "HK" => "Hong Kong",
    "HM" => "Heard Island & McDonald Islands",
    "HN" => "Honduras",
    "HR" => "Croatia",
    "HT" => "Haiti",
    "HU" => "Hungary",
    "ID" => "Indonesia",
    "IE" => "Ireland",
    "IL" => "Israel",
    "IM" => "Isle of Man",
    "IN" => "India",
    "IO" => "British Indian Ocean Territory",
    "IQ" => "Iraq",
    "IR" => "Iran",
    "IS" => "Iceland",
    "IT" => "Italy",
    "JE" => "Jersey",
    "JM" => "Jamaica",
    "JO" => "Jordan",
    "JP" => "Japan",
    "KE" => "Kenya",
    "KG" => "Kyrgyzstan",
    "KH" => "Cambodia",
    "KI" => "Kiribati",
    "KM" => "Comoros",
    "KN" => "St Kitts & Nevis",
    "KP" => "North Korea",
    "KR" => "South Korea",
    "KW" => "Kuwait",
    "KY" => "Cayman Islands",
    "KZ" => "Kazakhstan",
    "LA" => "Laos",
    "LB" => "Lebanon",
    "LC" => "St Lucia",
    "LI" => "Liechtenstein",
    "LK" => "Sri Lanka",
    "LR" => "Liberia",
    "LS" => "Lesotho",
    "LT" => "Lithuania",
    "LU" => "Luxembourg",
    "LV" => "Latvia",
    "LY" => "Libya",
    "MA" => "Morocco",
    "MC" => "Monaco",
    "MD" => "Moldova",
    "ME" => "Montenegro",
    "MF" => "St Martin (French)",
    "MG" => "Madagascar",
    "MH" => "Marshall Islands",
    "MK" => "North Macedonia",
    "ML" => "Mali",
    "MM" => "Myanmar",
    "MN" => "Mongolia",
    "MO" => "Macau",
    "MP" => "Northern Mariana Islands",
    "MQ" => "Martinique",
    "MR" => "Mauritania",
    "MS" => "Montserrat",
    "MT" => "Malta",
    "MU" => "Mauritius",
    "MV" => "Maldives",
    "MW" => "Malawi",
    "MX" => "Mexico",
    "MY" => "Malaysia",
    "MZ" => "Mozambique",
    "NA" => "Namibia",
    "NC" => "New Caledonia",
    "NE" => "Niger",
    "NF" => "Norfolk Island",
    "NG" => "Nigeria",
    "NI" => "Nicaragua",
    "NL" => "Netherlands",
    "NO" => "Norway",
    "NP" => "Nepal",
    "NR" => "Nauru",
    "NU" => "Niue",
    "NZ" => "New Zealand",
    "OM" => "Oman",
    "PA" => "Panama",
    "PE" => "Peru",
    "PF" => "French Polynesia",
    "PG" => "Papua New Guinea",
    "PH" => "Philippines",
    "PK" => "Pakistan",
    "PL" => "Poland",
    "PM" => "St Pierre & Miquelon",
    "PN" => "Pitcairn",
    "PR" => "Puerto Rico",
    "PS" => "Palestine",
    "PT" => "Portugal",
    "PW" => "Palau",
    "PY" => "Paraguay",
    "QA" => "Qatar",
    "RE" => "Réunion",
    "RO" => "Romania",
    "RS" => "Serbia",
    "RU" => "Russia",
    "RW" => "Rwanda",
    "SA" => "Saudi Arabia",
    "SB" => "Solomon Islands",
    "SC" => "Seychelles",
    "SD" => "Sudan",
    "SE" => "Sweden",
    "SG" => "Singapore",
    "SH" => "St Helena",
    "SI" => "Slovenia",
    "SJ" => "Svalbard & Jan Mayen",
    "SK" => "Slovakia",
    "SL" => "Sierra Leone",
    "SM" => "San Marino",
    "SN" => "Senegal",
    "SO" => "Somalia",
    "SR" => "Suriname",
    "SS" => "South Sudan",
    "ST" => "Sao Tome & Principe",
    "SV" => "El Salvador",
    "SX" => "St Maarten (Dutch)",
    "SY" => "Syria",
    "SZ" => "Eswatini",
    "TC" => "Turks & Caicos Is",
    "TD" => "Chad",
    "TF" => "French S. Terr.",
    "TG" => "Togo",
    "TH" => "Thailand",
    "TJ" => "Tajikistan",
    "TK" => "Tokelau",
    "TL" => "Timor-Leste",
    "TM" => "Turkmenistan",
    "TN" => "Tunisia",
    "TO" => "Tonga",
    "TR" => "Turkey",
    "TT" => "Trinidad & Tobago",
    "TV" => "Tuvalu",
    "TW" => "Taiwan",
    "TZ" => "Tanzania",
    "UA" => "Ukraine",
    "UG" => "Uganda",
    "UM" => "US minor outlying islands",
    "US" => "United States",
    "UY" => "Uruguay",
    "UZ" => "Uzbekistan",
    "VA" => "Vatican City",
    "VC" => "St Vincent",
    "VE" => "Venezuela",
    "VG" => "Virgin Islands (UK)",
    "VI" => "Virgin Islands (US)",
    "VN" => "Vietnam",
    "VU" => "Vanuatu",
    "WF" => "Wallis & Futuna",
    "WS" => "Samoa (western)",
    "YE" => "Yemen",
    "YT" => "Mayotte",
    "ZA" => "South Africa",
    "ZM" => "Zambia",
    "ZW" => "Zimbabwe"
  }

  @zone_countries %{
    "Africa/Abidjan" => "CI",
    "Africa/Accra" => "GH",
    "Africa/Addis_Ababa" => "ET",
    "Africa/Algiers" => "DZ",
    "Africa/Asmara" => "ER",
    "Africa/Bamako" => "ML",
    "Africa/Bangui" => "CF",
    "Africa/Banjul" => "GM",
    "Africa/Bissau" => "GW",
    "Africa/Blantyre" => "MW",
    "Africa/Brazzaville" => "CG",
    "Africa/Bujumbura" => "BI",
    "Africa/Cairo" => "EG",
    "Africa/Casablanca" => "MA",
    "Africa/Ceuta" => "ES",
    "Africa/Conakry" => "GN",
    "Africa/Dakar" => "SN",
    "Africa/Dar_es_Salaam" => "TZ",
    "Africa/Djibouti" => "DJ",
    "Africa/Douala" => "CM",
    "Africa/El_Aaiun" => "EH",
    "Africa/Freetown" => "SL",
    "Africa/Gaborone" => "BW",
    "Africa/Harare" => "ZW",
    "Africa/Johannesburg" => "ZA",
    "Africa/Juba" => "SS",
    "Africa/Kampala" => "UG",
    "Africa/Khartoum" => "SD",
    "Africa/Kigali" => "RW",
    "Africa/Kinshasa" => "CD",
    "Africa/Lagos" => "NG",
    "Africa/Libreville" => "GA",
    "Africa/Lome" => "TG",
    "Africa/Luanda" => "AO",
    "Africa/Lubumbashi" => "CD",
    "Africa/Lusaka" => "ZM",
    "Africa/Malabo" => "GQ",
    "Africa/Maputo" => "MZ",
    "Africa/Maseru" => "LS",
    "Africa/Mbabane" => "SZ",
    "Africa/Mogadishu" => "SO",
    "Africa/Monrovia" => "LR",
    "Africa/Nairobi" => "KE",
    "Africa/Ndjamena" => "TD",
    "Africa/Niamey" => "NE",
    "Africa/Nouakchott" => "MR",
    "Africa/Ouagadougou" => "BF",
    "Africa/Porto-Novo" => "BJ",
    "Africa/Sao_Tome" => "ST",
    "Africa/Tripoli" => "LY",
    "Africa/Tunis" => "TN",
    "Africa/Windhoek" => "NA",
    "America/Adak" => "US",
    "America/Anchorage" => "US",
    "America/Anguilla" => "AI",
    "America/Antigua" => "AG",
    "America/Araguaina" => "BR",
    "America/Argentina/Buenos_Aires" => "AR",
    "America/Argentina/Catamarca" => "AR",
    "America/Argentina/Cordoba" => "AR",
    "America/Argentina/Jujuy" => "AR",
    "America/Argentina/La_Rioja" => "AR",
    "America/Argentina/Mendoza" => "AR",
    "America/Argentina/Rio_Gallegos" => "AR",
    "America/Argentina/Salta" => "AR",
    "America/Argentina/San_Juan" => "AR",
    "America/Argentina/San_Luis" => "AR",
    "America/Argentina/Tucuman" => "AR",
    "America/Argentina/Ushuaia" => "AR",
    "America/Aruba" => "AW",
    "America/Asuncion" => "PY",
    "America/Atikokan" => "CA",
    "America/Bahia" => "BR",
    "America/Bahia_Banderas" => "MX",
    "America/Barbados" => "BB",
    "America/Belem" => "BR",
    "America/Belize" => "BZ",
    "America/Blanc-Sablon" => "CA",
    "America/Boa_Vista" => "BR",
    "America/Bogota" => "CO",
    "America/Boise" => "US",
    "America/Buenos_Aires" => "AR",
    "America/Cambridge_Bay" => "CA",
    "America/Campo_Grande" => "BR",
    "America/Cancun" => "MX",
    "America/Caracas" => "VE",
    "America/Cayenne" => "GF",
    "America/Cayman" => "KY",
    "America/Chicago" => "US",
    "America/Chihuahua" => "MX",
    "America/Ciudad_Juarez" => "MX",
    "America/Costa_Rica" => "CR",
    "America/Coyhaique" => "CL",
    "America/Creston" => "CA",
    "America/Cuiaba" => "BR",
    "America/Curacao" => "CW",
    "America/Danmarkshavn" => "GL",
    "America/Dawson" => "CA",
    "America/Dawson_Creek" => "CA",
    "America/Denver" => "US",
    "America/Detroit" => "US",
    "America/Dominica" => "DM",
    "America/Edmonton" => "CA",
    "America/Eirunepe" => "BR",
    "America/El_Salvador" => "SV",
    "America/Fort_Nelson" => "CA",
    "America/Fortaleza" => "BR",
    "America/Glace_Bay" => "CA",
    "America/Godthab" => "GL",
    "America/Goose_Bay" => "CA",
    "America/Grand_Turk" => "TC",
    "America/Grenada" => "GD",
    "America/Guadeloupe" => "GP",
    "America/Guatemala" => "GT",
    "America/Guayaquil" => "EC",
    "America/Guyana" => "GY",
    "America/Halifax" => "CA",
    "America/Havana" => "CU",
    "America/Hermosillo" => "MX",
    "America/Indiana/Indianapolis" => "US",
    "America/Indiana/Knox" => "US",
    "America/Indiana/Marengo" => "US",
    "America/Indiana/Petersburg" => "US",
    "America/Indiana/Tell_City" => "US",
    "America/Indiana/Vevay" => "US",
    "America/Indiana/Vincennes" => "US",
    "America/Indiana/Winamac" => "US",
    "America/Indianapolis" => "US",
    "America/Inuvik" => "CA",
    "America/Iqaluit" => "CA",
    "America/Jamaica" => "JM",
    "America/Juneau" => "US",
    "America/Kentucky/Louisville" => "US",
    "America/Kentucky/Monticello" => "US",
    "America/Kralendijk" => "BQ",
    "America/La_Paz" => "BO",
    "America/Lima" => "PE",
    "America/Los_Angeles" => "US",
    "America/Lower_Princes" => "SX",
    "America/Maceio" => "BR",
    "America/Managua" => "NI",
    "America/Manaus" => "BR",
    "America/Marigot" => "MF",
    "America/Martinique" => "MQ",
    "America/Matamoros" => "MX",
    "America/Mazatlan" => "MX",
    "America/Menominee" => "US",
    "America/Merida" => "MX",
    "America/Metlakatla" => "US",
    "America/Mexico_City" => "MX",
    "America/Miquelon" => "PM",
    "America/Moncton" => "CA",
    "America/Monterrey" => "MX",
    "America/Montevideo" => "UY",
    "America/Montreal" => "CA",
    "America/Montserrat" => "MS",
    "America/Nassau" => "BS",
    "America/New_York" => "US",
    "America/Nome" => "US",
    "America/Noronha" => "BR",
    "America/North_Dakota/Beulah" => "US",
    "America/North_Dakota/Center" => "US",
    "America/North_Dakota/New_Salem" => "US",
    "America/Nuuk" => "GL",
    "America/Ojinaga" => "MX",
    "America/Panama" => "PA",
    "America/Paramaribo" => "SR",
    "America/Phoenix" => "US",
    "America/Port-au-Prince" => "HT",
    "America/Port_of_Spain" => "TT",
    "America/Porto_Velho" => "BR",
    "America/Puerto_Rico" => "PR",
    "America/Punta_Arenas" => "CL",
    "America/Rankin_Inlet" => "CA",
    "America/Recife" => "BR",
    "America/Regina" => "CA",
    "America/Resolute" => "CA",
    "America/Rio_Branco" => "BR",
    "America/Santarem" => "BR",
    "America/Santiago" => "CL",
    "America/Santo_Domingo" => "DO",
    "America/Sao_Paulo" => "BR",
    "America/Scoresbysund" => "GL",
    "America/Sitka" => "US",
    "America/St_Barthelemy" => "BL",
    "America/St_Johns" => "CA",
    "America/St_Kitts" => "KN",
    "America/St_Lucia" => "LC",
    "America/St_Thomas" => "VI",
    "America/St_Vincent" => "VC",
    "America/Swift_Current" => "CA",
    "America/Tegucigalpa" => "HN",
    "America/Thule" => "GL",
    "America/Tijuana" => "MX",
    "America/Toronto" => "CA",
    "America/Tortola" => "VG",
    "America/Vancouver" => "CA",
    "America/Whitehorse" => "CA",
    "America/Winnipeg" => "CA",
    "America/Yakutat" => "US",
    "Antarctica/Casey" => "AQ",
    "Antarctica/Davis" => "AQ",
    "Antarctica/DumontDUrville" => "AQ",
    "Antarctica/Macquarie" => "AU",
    "Antarctica/Mawson" => "AQ",
    "Antarctica/McMurdo" => "AQ",
    "Antarctica/Palmer" => "AQ",
    "Antarctica/Rothera" => "AQ",
    "Antarctica/Syowa" => "AQ",
    "Antarctica/Troll" => "AQ",
    "Antarctica/Vostok" => "AQ",
    "Arctic/Longyearbyen" => "SJ",
    "Asia/Aden" => "YE",
    "Asia/Almaty" => "KZ",
    "Asia/Amman" => "JO",
    "Asia/Anadyr" => "RU",
    "Asia/Aqtau" => "KZ",
    "Asia/Aqtobe" => "KZ",
    "Asia/Ashgabat" => "TM",
    "Asia/Atyrau" => "KZ",
    "Asia/Baghdad" => "IQ",
    "Asia/Bahrain" => "BH",
    "Asia/Baku" => "AZ",
    "Asia/Bangkok" => "TH",
    "Asia/Barnaul" => "RU",
    "Asia/Beirut" => "LB",
    "Asia/Bishkek" => "KG",
    "Asia/Brunei" => "BN",
    "Asia/Calcutta" => "IN",
    "Asia/Chita" => "RU",
    "Asia/Chongqing" => "CN",
    "Asia/Colombo" => "LK",
    "Asia/Damascus" => "SY",
    "Asia/Dhaka" => "BD",
    "Asia/Dili" => "TL",
    "Asia/Dubai" => "AE",
    "Asia/Dushanbe" => "TJ",
    "Asia/Famagusta" => "CY",
    "Asia/Gaza" => "PS",
    "Asia/Harbin" => "CN",
    "Asia/Hebron" => "PS",
    "Asia/Ho_Chi_Minh" => "VN",
    "Asia/Hong_Kong" => "HK",
    "Asia/Hovd" => "MN",
    "Asia/Irkutsk" => "RU",
    "Asia/Jakarta" => "ID",
    "Asia/Jayapura" => "ID",
    "Asia/Jerusalem" => "IL",
    "Asia/Kabul" => "AF",
    "Asia/Kamchatka" => "RU",
    "Asia/Karachi" => "PK",
    "Asia/Kathmandu" => "NP",
    "Asia/Katmandu" => "NP",
    "Asia/Khandyga" => "RU",
    "Asia/Kolkata" => "IN",
    "Asia/Krasnoyarsk" => "RU",
    "Asia/Kuala_Lumpur" => "MY",
    "Asia/Kuching" => "MY",
    "Asia/Kuwait" => "KW",
    "Asia/Macau" => "MO",
    "Asia/Magadan" => "RU",
    "Asia/Makassar" => "ID",
    "Asia/Manila" => "PH",
    "Asia/Muscat" => "OM",
    "Asia/Nicosia" => "CY",
    "Asia/Novokuznetsk" => "RU",
    "Asia/Novosibirsk" => "RU",
    "Asia/Omsk" => "RU",
    "Asia/Oral" => "KZ",
    "Asia/Phnom_Penh" => "KH",
    "Asia/Pontianak" => "ID",
    "Asia/Pyongyang" => "KP",
    "Asia/Qatar" => "QA",
    "Asia/Qostanay" => "KZ",
    "Asia/Qyzylorda" => "KZ",
    "Asia/Rangoon" => "MM",
    "Asia/Riyadh" => "SA",
    "Asia/Saigon" => "VN",
    "Asia/Sakhalin" => "RU",
    "Asia/Samarkand" => "UZ",
    "Asia/Seoul" => "KR",
    "Asia/Shanghai" => "CN",
    "Asia/Singapore" => "SG",
    "Asia/Srednekolymsk" => "RU",
    "Asia/Taipei" => "TW",
    "Asia/Tashkent" => "UZ",
    "Asia/Tbilisi" => "GE",
    "Asia/Tehran" => "IR",
    "Asia/Thimphu" => "BT",
    "Asia/Tokyo" => "JP",
    "Asia/Tomsk" => "RU",
    "Asia/Ulaanbaatar" => "MN",
    "Asia/Urumqi" => "CN",
    "Asia/Ust-Nera" => "RU",
    "Asia/Vientiane" => "LA",
    "Asia/Vladivostok" => "RU",
    "Asia/Yakutsk" => "RU",
    "Asia/Yangon" => "MM",
    "Asia/Yekaterinburg" => "RU",
    "Asia/Yerevan" => "AM",
    "Atlantic/Azores" => "PT",
    "Atlantic/Bermuda" => "BM",
    "Atlantic/Canary" => "ES",
    "Atlantic/Cape_Verde" => "CV",
    "Atlantic/Faeroe" => "FO",
    "Atlantic/Faroe" => "FO",
    "Atlantic/Madeira" => "PT",
    "Atlantic/Reykjavik" => "IS",
    "Atlantic/South_Georgia" => "GS",
    "Atlantic/St_Helena" => "SH",
    "Atlantic/Stanley" => "FK",
    "Australia/Adelaide" => "AU",
    "Australia/Brisbane" => "AU",
    "Australia/Broken_Hill" => "AU",
    "Australia/Darwin" => "AU",
    "Australia/Eucla" => "AU",
    "Australia/Hobart" => "AU",
    "Australia/Lindeman" => "AU",
    "Australia/Lord_Howe" => "AU",
    "Australia/Melbourne" => "AU",
    "Australia/NSW" => "AU",
    "Australia/Perth" => "AU",
    "Australia/Queensland" => "AU",
    "Australia/Sydney" => "AU",
    "Australia/West" => "AU",
    "Canada/Central" => "CA",
    "Canada/Eastern" => "CA",
    "Canada/Pacific" => "CA",
    "Cuba" => "CU",
    "Egypt" => "EG",
    "Eire" => "IE",
    "Europe/Amsterdam" => "NL",
    "Europe/Andorra" => "AD",
    "Europe/Astrakhan" => "RU",
    "Europe/Athens" => "GR",
    "Europe/Belfast" => "GB",
    "Europe/Belgrade" => "RS",
    "Europe/Berlin" => "DE",
    "Europe/Bratislava" => "SK",
    "Europe/Brussels" => "BE",
    "Europe/Bucharest" => "RO",
    "Europe/Budapest" => "HU",
    "Europe/Busingen" => "DE",
    "Europe/Chisinau" => "MD",
    "Europe/Copenhagen" => "DK",
    "Europe/Dublin" => "IE",
    "Europe/Gibraltar" => "GI",
    "Europe/Guernsey" => "GG",
    "Europe/Helsinki" => "FI",
    "Europe/Isle_of_Man" => "IM",
    "Europe/Istanbul" => "TR",
    "Europe/Jersey" => "JE",
    "Europe/Kaliningrad" => "RU",
    "Europe/Kiev" => "UA",
    "Europe/Kirov" => "RU",
    "Europe/Kyiv" => "UA",
    "Europe/Lisbon" => "PT",
    "Europe/Ljubljana" => "SI",
    "Europe/London" => "GB",
    "Europe/Luxembourg" => "LU",
    "Europe/Madrid" => "ES",
    "Europe/Malta" => "MT",
    "Europe/Mariehamn" => "AX",
    "Europe/Minsk" => "BY",
    "Europe/Monaco" => "MC",
    "Europe/Moscow" => "RU",
    "Europe/Nicosia" => "CY",
    "Europe/Oslo" => "NO",
    "Europe/Paris" => "FR",
    "Europe/Podgorica" => "ME",
    "Europe/Prague" => "CZ",
    "Europe/Riga" => "LV",
    "Europe/Rome" => "IT",
    "Europe/Samara" => "RU",
    "Europe/San_Marino" => "SM",
    "Europe/Sarajevo" => "BA",
    "Europe/Saratov" => "RU",
    "Europe/Simferopol" => "UA",
    "Europe/Skopje" => "MK",
    "Europe/Sofia" => "BG",
    "Europe/Stockholm" => "SE",
    "Europe/Tallinn" => "EE",
    "Europe/Tirane" => "AL",
    "Europe/Ulyanovsk" => "RU",
    "Europe/Vaduz" => "LI",
    "Europe/Vatican" => "VA",
    "Europe/Vienna" => "AT",
    "Europe/Vilnius" => "LT",
    "Europe/Volgograd" => "RU",
    "Europe/Warsaw" => "PL",
    "Europe/Zagreb" => "HR",
    "Europe/Zurich" => "CH",
    "GB" => "GB",
    "Hongkong" => "HK",
    "Iceland" => "IS",
    "Indian/Antananarivo" => "MG",
    "Indian/Chagos" => "IO",
    "Indian/Christmas" => "CX",
    "Indian/Cocos" => "CC",
    "Indian/Comoro" => "KM",
    "Indian/Kerguelen" => "TF",
    "Indian/Mahe" => "SC",
    "Indian/Maldives" => "MV",
    "Indian/Mauritius" => "MU",
    "Indian/Mayotte" => "YT",
    "Indian/Reunion" => "RE",
    "Iran" => "IR",
    "Israel" => "IL",
    "Jamaica" => "JM",
    "Japan" => "JP",
    "Libya" => "LY",
    "NZ" => "NZ",
    "Pacific/Apia" => "WS",
    "Pacific/Auckland" => "NZ",
    "Pacific/Bougainville" => "PG",
    "Pacific/Chatham" => "NZ",
    "Pacific/Chuuk" => "FM",
    "Pacific/Easter" => "CL",
    "Pacific/Efate" => "VU",
    "Pacific/Fakaofo" => "TK",
    "Pacific/Fiji" => "FJ",
    "Pacific/Funafuti" => "TV",
    "Pacific/Galapagos" => "EC",
    "Pacific/Gambier" => "PF",
    "Pacific/Guadalcanal" => "SB",
    "Pacific/Guam" => "GU",
    "Pacific/Honolulu" => "US",
    "Pacific/Kanton" => "KI",
    "Pacific/Kiritimati" => "KI",
    "Pacific/Kosrae" => "FM",
    "Pacific/Kwajalein" => "MH",
    "Pacific/Majuro" => "MH",
    "Pacific/Marquesas" => "PF",
    "Pacific/Midway" => "UM",
    "Pacific/Nauru" => "NR",
    "Pacific/Niue" => "NU",
    "Pacific/Norfolk" => "NF",
    "Pacific/Noumea" => "NC",
    "Pacific/Pago_Pago" => "AS",
    "Pacific/Palau" => "PW",
    "Pacific/Pitcairn" => "PN",
    "Pacific/Pohnpei" => "FM",
    "Pacific/Ponape" => "FM",
    "Pacific/Port_Moresby" => "PG",
    "Pacific/Rarotonga" => "CK",
    "Pacific/Saipan" => "MP",
    "Pacific/Tahiti" => "PF",
    "Pacific/Tarawa" => "KI",
    "Pacific/Tongatapu" => "TO",
    "Pacific/Truk" => "FM",
    "Pacific/Wake" => "UM",
    "Pacific/Wallis" => "WF",
    "Poland" => "PL",
    "Portugal" => "PT",
    "Singapore" => "SG",
    "Turkey" => "TR",
    "US/Alaska" => "US",
    "US/Central" => "US",
    "US/Eastern" => "US",
    "US/Hawaii" => "US",
    "US/Mountain" => "US",
    "US/Pacific" => "US"
  }

  @doc "Country name for an ISO 3166-1 alpha-2 code, or nil."
  def name(nil), do: nil

  def name(code) when is_binary(code) do
    Map.get(@countries, String.upcase(code))
  end

  def name(_), do: nil

  @doc "Whether a string is a country code this module knows."
  def known?(code) when is_binary(code), do: Map.has_key?(@countries, String.upcase(code))
  def known?(_), do: false

  @doc "Best-guess ISO country code for an IANA time zone, or nil."
  def country_for_zone(nil), do: nil

  def country_for_zone(zone) when is_binary(zone) do
    Map.get(@zone_countries, zone)
  end

  def country_for_zone(_), do: nil

  @doc """
  ISO code for a country name, or nil.

  Callers of the ping API send whatever their own data holds — "United States",
  "USA", "us" — so the name is matched case-insensitively and a two-letter value
  is treated as a code.
  """
  def code_for(nil), do: nil

  def code_for(value) when is_binary(value) do
    trimmed = String.trim(value)
    upcased = String.upcase(trimmed)

    cond do
      Map.has_key?(@countries, upcased) -> upcased
      true -> lookup_by_name(String.downcase(trimmed))
    end
  end

  def code_for(_), do: nil

  @by_name Map.new(@countries, fn {code, name} -> {String.downcase(name), code} end)

  @aliases %{
    "usa" => "US",
    "u.s." => "US",
    "u.s.a." => "US",
    "united states of america" => "US",
    "uk" => "GB",
    "great britain" => "GB",
    "england" => "GB",
    "scotland" => "GB",
    "wales" => "GB",
    "northern ireland" => "GB",
    "britain" => "GB",
    "south korea" => "KR",
    "north korea" => "KP",
    "republic of korea" => "KR",
    "russia" => "RU",
    "russian federation" => "RU",
    "vietnam" => "VN",
    "viet nam" => "VN",
    "czech republic" => "CZ",
    "holland" => "NL",
    "the netherlands" => "NL",
    "uae" => "AE",
    "ivory coast" => "CI",
    "burma" => "MM"
  }

  defp lookup_by_name(name) do
    Map.get(@by_name, name) || Map.get(@aliases, name)
  end

  @doc "Number of countries in the table."
  def count, do: map_size(@countries)

  @doc "Number of time zones in the table."
  def zone_count, do: map_size(@zone_countries)
end
